### ISSUE TITLE
attachments package is outdated kanso push fails on node > 0.10

### ISSUE THREAD

**Issue by mandric** [garden20/dashboard#102]
For some reason we have committed packages to the repo.  The `packages` directory should be managed by `kanso`.  

Find out which monkey patches have been applied to that directory and either apply them upstream or monkey patch a better way.

**Comment by mandric** [comment]
Example stack trace:

```
Error: Error: No such module: evals
   at Error (native)
   at Object.<anonymous> (/Users/estellecomment/dev/medic/medic-webapp/dashboard-tmp/packages/attachments/node_modules/kanso-utils/utils.js:12:21)
   at Module._compile (module.js:435:26)
   at Object.Module._extensions..js (module.js:442:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:311:12)
   at Module.require (module.js:366:17)
   at require (module.js:385:17)
   at Object.<anonymous> (/Users/estellecomment/dev/medic/medic-webapp/dashboard-tmp/packages/attachments/node_modules/kanso-utils/attachments.js:8:13)
   at Module._compile (module.js:435:26)
Failed
```
